config/routes.rb
Mblizz::Application.routes.draw do
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root 'pages#home'
  match '/help', to: 'pages#help', via: 'get'
  match '/about', to: 'pages#about', via: 'get'
  match '/contact', to: 'pages#contact', via: 'get'
  match '/terms', to: 'pages#terms', via: 'get'
  match '/privacy', to: 'pages#privacy', via: 'get'
  match '/team', to: 'pages#team', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/views/shared/_error_messages.html.erb
<div id = "error_explain">
  <% if object.errors.any? %>
    <div class = "alert alert-danger">This form has  <%= pluralize(object.errors.count, "error") %></div>
    <ul>
      <% object.errors.full_messages.each do |err| %>
        <li> <%= err %> </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class = "microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id = "<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class = "user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class = "content"><%= wrap(feed_item.content) %></span>
  <span class = "timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to 'Delete', feed_item, method: :delete, data: { confirm: 'Sure?' }, title: feed_item.content %>
  <% end %>
</li>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class = "field">
    <%= f.text_area :content, placeholder: "Create new post...", id: "micropost_text" %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<% followin = @user.followed_users.count %>
<% followe = @user.followers.count %>
<div class = "stats">
  <%= link_to "#{followin} Following", following_user_path(@user), class: "stat", id: "following" %>
  <%= link_to "#{followe} Followers", followers_user_path(@user), class: "stat", id: "followers" %>
</div>

app/views/shared/_user_info.html.erb
<h1>
  <%= link_to (gravatar_for(current_user, size: 100)), current_user %>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "View my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "microposts") %>
</span>