config/routes.rb
Mblizz::Application.routes.draw do
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root 'pages#home'
  match '/help', to: 'pages#help', via: 'get'
  match '/about', to: 'pages#about', via: 'get'
  match '/contact', to: 'pages#contact', via: 'get'
  match '/terms', to: 'pages#terms', via: 'get'
  match '/privacy', to: 'pages#privacy', via: 'get'
  match '/team', to: 'pages#team', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/views/layouts/_footer.html.erb
<footer class = "footer">
  <small>Mania Technologies</small>
  <nav class = "nav-footer">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact Us", contact_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "Terms & Conditions", terms_path %></li>
      <li><%= link_to "Privacy Policy", privacy_path %></li>
      <li><%= link_to "Team", team_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class = "navbar navbar-fixed-top navbar-inverse">
  <div class = "navbar-inner">
    <div class = "container">
      <%= link_to "MBlizz", root_path, id: "logo" %>
      <nav>
        <ul class = "nav pull-right" id = "header-ul">
          <li><%= link_to 'Home', root_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id = "fat-menu" class = "drop-down">
              <a href="#" class = "dropdown-toggle" data-toggle = "dropdown"> Account <b class = "caret"></b></a>
              <ul class = "dropdown-menu">
                <li><%= link_to "Profile", user_path(current_user) %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li><%= link_to "Sign out", signout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
            <li><%= link_to "Register", signup_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE9]>
      <script src = "http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class = "container">
      <% flash.each do |key, value| %>
        <div class = "alert alert-<%= key %>"><%= value %></div>
      <% end %> 
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <br><br>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>